### ISSUE TITLE
Files aren't highlighted on selection using buttons

### ISSUE THREAD

**Issue by PhungThanhTu** [catppuccin/obsidian#60] opened 2024-05-19 12:39 UTC
I came across a weird situation where the folders are highlighted with a gray bordered box when highlighted, but files aren't highlighted.

### Folders:

![image](https://github.com/catppuccin/obsidian/assets/67744403/daf41f0a-dd45-40a2-8d3f-29bdc4c7228d)

### Files:

It just disappeared.

![image](https://github.com/catppuccin/obsidian/assets/67744403/f66b40ec-6b75-40dc-9b5c-9093b4296c49)

## Context (Default theme)

It works normally on default themes.

### Folders

![image](https://github.com/catppuccin/obsidian/assets/67744403/e12071cf-a65b-41f9-ae05-581cf22f3d4d)

### Files

![image](https://github.com/catppuccin/obsidian/assets/67744403/4657ee62-2782-4859-b13b-47e945a34f7c)

## Context (Other themes such as Dracula)

It also works on other themes (I picked Dracula Official).

### Folders

![image](https://github.com/catppuccin/obsidian/assets/67744403/3d6d250f-1a1b-4e55-9e85-af144aeef585)

### Files 

![image](https://github.com/catppuccin/obsidian/assets/67744403/b05c98f6-3ef7-4e18-880c-9de7c4c665d4)

**Comment by mbeckrich** [comment] 2024-05-19 14:05
I’ll try to take a look at this today and get a fix out. Appreciate the details!On May 19, 2024, at 6:40 AM, TuPT ***@***.***> wrote:﻿
I came across a weird situation where the folders are highlighted with a gray bordered box when highlighted, but files aren't highlighted.
Context (Catppuccin)
Folders:
image.png (view on web)
Files:
It just disappeared.
image.png (view on web)
Context (Default theme)
It works normally on default themes.
Folders
image.png (view on web)
Files
image.png (view on web)
Context (Other themes such as Dracula)
It also works on other themes (I picked Dracula Official).
Folders
image.png (view on web)
Files
image.png (view on web)

**Comment by mbeckrich** [comment] 2024-05-19 16:13
I'm having some difficulty replicating this. I want to make sure we're using the term 'highlighting' the same way. When I hover my cursor over a file or folder name, I see this:

![image](https://github.com/catppuccin/obsidian/assets/88514414/6be5967e-c549-413f-8565-2aca66f51861)

When I hover over an 'active' (i.e., clicked on file), I see this (it changes from pink, the active color, to blue):

![Screenshot 2024-05-19 at 10 01 11 AM](https://github.com/catppuccin/obsidian/assets/88514414/5fe533ed-915f-49eb-bc90-d2ac578746d1)

I notice that it looks like you have changed the color of file names in the theme. Have you adjusted any css through a snippet (or plugin) that might interact with the theme in a way that could cause this? It looks like the snippet is on in the sample from the default theme and off in Dracula (or Dracula supersedes/ignores the snippet), but I wonder if something is going on there? Happy to keep looking into this, just want to make sure I understand where the issue is coming from. :) One possibility is that if you have turned off the hover color on file/folder names, there is css either in or missing from your snippet or Catppuccin that causes the grey border to exist in one case but not the other.

**Comment by PhungThanhTu** [comment] 2024-05-21 07:14
@mbeckrich 
I tried by disabling all other plugins, including "style setting" which is used to change to the "Frappe" flavor, the issue still persists.
And the highlight border box is appeared when we traverse through the files using arrow buttons.
I made a comparison here for mouse hover (the pink colored) and button traverse (the border box).
![image](https://github.com/catppuccin/obsidian/assets/67744403/7e1b2912-c0aa-47a8-bb41-ff5b35ba43fd)

**Comment by mbeckrich** [comment] 2024-05-22 05:27
Thanks! I was able to better understand what was wrong now. I have pushed a fix in https://github.com/catppuccin/obsidian/commit/8f8c8bb9b19bcbeb2667a76b5417fc52170ae027. Reopen this issue and let me know if you run into further issues -- hopefully I didn't break anything. :) I don't use the arrow keys in Obsidian, so I might have missed something, but this fix seems to work for both light and dark mode.

**Closed by mbeckrich** 2024-05-22 05:27 UTC
